# Generated by Django 5.1.1 on 2024-09-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
